// Push every AI Visibility scan into Zoho CRM as an "Inquiry" / Nurture Lead.
//
// Scan form only captures website domain (no email), so we use a placeholder
// email pattern (scan+<sanitized-domain>@thrive-tracker.local) per Aaron's
// 2026-05-26 decision. When a real form fill happens later, the Form receiver
// upserts the Lead with the real email and graduates status from Inquiry → MQL.
//
// Failure-safe: never blocks the scan response. Errors logged + swallowed.

const ZOHO_CLIENT_ID = process.env.ZOHO_CLIENT_ID || '';
const ZOHO_CLIENT_SECRET = process.env.ZOHO_CLIENT_SECRET || '';
const ZOHO_REFRESH_TOKEN = process.env.ZOHO_REFRESH_TOKEN || '';
const ZOHO_API_BASE = process.env.ZOHO_API_BASE || 'https://www.zohoapis.com/crm/v2';
const ZOHO_AUTH_BASE = process.env.ZOHO_AUTH_BASE || 'https://accounts.zoho.com/oauth/v2';

// Token cache (Zoho access tokens last 1h; refresh on demand)
let cachedToken = null;
let cachedExpiresAt = 0;

async function getAccessToken() {
  if (cachedToken && Date.now() < cachedExpiresAt - 60_000) return cachedToken;
  if (!ZOHO_CLIENT_ID || !ZOHO_CLIENT_SECRET || !ZOHO_REFRESH_TOKEN) {
    throw new Error('Zoho credentials missing — set ZOHO_CLIENT_ID, ZOHO_CLIENT_SECRET, ZOHO_REFRESH_TOKEN');
  }
  const body = new URLSearchParams({
    refresh_token: ZOHO_REFRESH_TOKEN,
    client_id: ZOHO_CLIENT_ID,
    client_secret: ZOHO_CLIENT_SECRET,
    grant_type: 'refresh_token',
  }).toString();
  const resp = await fetch(`${ZOHO_AUTH_BASE}/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body,
  });
  const data = await resp.json();
  if (!data.access_token) throw new Error('Zoho token refresh failed: ' + JSON.stringify(data));
  cachedToken = data.access_token;
  cachedExpiresAt = Date.now() + (data.expires_in || 3600) * 1000;
  return cachedToken;
}

function sanitizeDomain(url) {
  try {
    const host = new URL(/^https?:\/\//i.test(url) ? url : 'https://' + url).hostname;
    return host.replace(/^www\./, '').toLowerCase();
  } catch {
    return String(url || '').replace(/^https?:\/\//, '').replace(/[^a-z0-9.-]/gi, '').toLowerCase();
  }
}

function brandFromDomain(domain) {
  const base = domain.split('.')[0].replace(/[-_]+/g, ' ').trim();
  return base ? base.charAt(0).toUpperCase() + base.slice(1) : 'Unknown';
}

/**
 * Create a Zoho Lead from an AI scan submission.
 * @param {object} scan - { scanId, websiteUrl, brand, ip, ua, referer, gclid, utm }
 * @returns {Promise<{lead_id?: string, skipped?: boolean, error?: string}>}
 */
async function pushScanToZoho(scan) {
  if (!ZOHO_CLIENT_ID || !ZOHO_REFRESH_TOKEN) {
    console.log('[zoho-nurture] credentials missing — skipping');
    return { skipped: true };
  }
  const domain = sanitizeDomain(scan.websiteUrl);
  if (!domain) return { skipped: true };

  const brand = scan.brand || brandFromDomain(domain);
  const placeholderEmail = `scan+${domain.replace(/[^a-z0-9.-]/g, '')}@thrive-tracker.local`;
  const u = scan.utm || {};

  // Lead description encodes the scan context so SDRs can read it later.
  const description = [
    `AI Visibility Scanner Inquiry — auto-created from scan #${scan.scanId}`,
    ``,
    `Domain scanned: ${scan.websiteUrl}`,
    `Scan URL: https://thrive-ai-visibility.onrender.com/report/${scan.scanId}`,
    `PDF report: https://thrive-report-app.onrender.com/api/url-to-pdf?url=${encodeURIComponent('https://thrive-ai-visibility.onrender.com/report/' + scan.scanId)}&filename=AI_Scan_${domain}_${new Date().toISOString().slice(0,10)}.pdf`,
    ``,
    `Visitor signals:`,
    `  IP address: ${scan.ip || '(none)'}`,
    `  User agent: ${scan.ua || '(none)'}`,
    `  Referer: ${scan.referer || '(none)'}`,
    `  Origin LP: ${scan.origin || '(none)'}`,
    ``,
    `Ad attribution:`,
    `  GCLID: ${scan.gclid || '(none)'}`,
    `  utm_source: ${u.source || '(none)'}`,
    `  utm_medium: ${u.medium || '(none)'}`,
    `  utm_campaign: ${u.campaign || '(none)'}`,
    `  utm_content: ${u.content || '(none)'}`,
    `  utm_term: ${u.term || '(none)'}`,
    ``,
    `--- Auto-generated by thrive-ai-visibility — graduate to MQL when contact provides real email ---`,
  ].join('\n');

  const payload = {
    data: [{
      Last_Name: brand,                            // required by Zoho
      Company: brand,                              // required by Zoho
      Email: placeholderEmail,
      Website: scan.websiteUrl,
      Lead_Source: 'AI Visibility Scanner',
      Lead_Status: 'Pre Qualified',                // closest Zoho pick-list value to "Inquiry"
      Description: description,
      // Custom fields if they exist (Zoho silently ignores unknown fields)
      gclid: scan.gclid || '',
      utm_source: u.source || '',
      utm_medium: u.medium || '',
      utm_campaign: u.campaign || '',
      utm_content: u.content || '',
      utm_term: u.term || '',
    }],
    // upsert prevents duplicate Lead records if the same scan-domain comes back later;
    // duplicate_check_fields uses Email to identify the dup.
    duplicate_check_fields: ['Email'],
    trigger: [],  // empty array disables workflows on these auto-leads
  };

  try {
    const token = await getAccessToken();
    const resp = await fetch(`${ZOHO_API_BASE}/Leads/upsert`, {
      method: 'POST',
      headers: {
        'Authorization': `Zoho-oauthtoken ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });
    const data = await resp.json();
    if (!resp.ok || !data.data || !data.data[0]) {
      console.error('[zoho-nurture] error:', resp.status, JSON.stringify(data).slice(0, 400));
      return { error: `Zoho ${resp.status}` };
    }
    const result = data.data[0];
    if (result.code === 'SUCCESS') {
      const action = result.action || 'created';
      console.log(`[zoho-nurture] ${action} lead ${result.details?.id} for ${domain}`);
      return { lead_id: result.details?.id, action };
    } else {
      console.error('[zoho-nurture] non-success:', JSON.stringify(result).slice(0, 400));
      return { error: result.message || 'unknown' };
    }
  } catch (err) {
    console.error('[zoho-nurture] network/auth error:', err.message);
    return { error: err.message };
  }
}

module.exports = { pushScanToZoho };
